import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiMongodb,
  SiExpress,
  SiVite,
  SiStripe,
} from "react-icons/si";
import { FaNetworkWired } from "react-icons/fa";

export const projects = [
  {
    title: "FitZone",
    slug: "fitzone",
    category: "Full Stack",
    date: "2026-06-15",
    timeline: "6 Weeks",
    shortDesc: "A complete fitness platform connecting gym members, trainers, and admins.",
    description: "FitZone is a full-stack fitness and gym management platform that connects Members, Trainers, and Admins in one seamless ecosystem. Users can discover and book fitness classes, join community discussions, track their fitness journey, while admins manage users, trainers, classes, and platform activities through role-based dashboards.",
    overview: "Building a health platform comes with unique challenges, primarily regarding role management and payment processing. FitZone solves this by uniting gym management, community building, and class booking into a single pane of glass. Target users range from casual gym-goers looking to book their weekly sessions to facility administrators needing deep metrics on class attendance and revenue generation.",
    features: [
      "Role-based dashboards (Admin, Trainer, Member)",
      "Real-time fitness class booking system",
      "Integrated Stripe payment processing",
      "Community discussion forums and activity feeds",
      "Trainer profile and scheduling management",
    ],
    challenges: "The most challenging technical hurdle was managing real-time inventory for class slots while simultaneously processing Stripe transactions without race conditions. I implemented atomic database transactions and webhooks to ensure booking integrity. This project significantly deepened my understanding of distributed state management and third-party API integration.",
    futureImprovements: [
      "Implement an advanced admin analytics dashboard for revenue and class attendance tracking.",
      "Integrate in-app push notifications for class reminders and schedule changes.",
      "Expand the community feature with user-to-user direct messaging.",
      "Optimize database queries and implement caching for faster load times during peak booking hours."
    ],
    tech: ["Next.js", "Express.js", "MongoDB", "Better Auth", "Tailwind CSS", "HeroUI", "Stripe"],
    techIcons: [
      { name: "Next.js", icon: SiNextdotjs, color: "text-text-main dark:text-white" },
      { name: "Express.js", icon: SiExpress, color: "text-text-main dark:text-white" },
      { name: "MongoDB", icon: SiMongodb, color: "text-[#47A248]" },
      { name: "Tailwind CSS", icon: SiTailwindcss, color: "text-[#06B6D4]" },
      { name: "Stripe", icon: SiStripe, color: "text-[#008CDD]" },
    ],
    liveUrl: "https://fit-zone-client.vercel.app/",
    githubClient: "https://github.com/mehedi-ts/Fit-zone-client",
    githubServer: "https://github.com/mehedi-ts/Fit-zone-server",
    metrics: "FitZone",
    image: "https://i.ibb.co.com/6Jf3vNmg/d48ea52e-86fe-42bb-8aaf-76c711171b0d.png",
  },
  {
    title: "StudyNook",
    slug: "studynook",
    category: "Full Stack",
    date: "2026-05-10",
    timeline: "4 Weeks",
    shortDesc: "A study room booking engine for libraries and shared spaces.",
    description: "StudyNook is a full-stack web application that allows users to browse, search, and book study rooms in libraries or shared study spaces. Room owners can create and manage their listings, while users can book available time slots based on real-time availability.",
    overview: "As remote work and studying grow, finding quiet, dedicated spaces has become a premium commodity. StudyNook acts as a micro-booking engine tailored explicitly for short-term study space rentals. Users can filter by amenities, capacity, and real-time availability to secure their perfect study spot instantly.",
    features: [
      "Dynamic search and filtering by location/amenities",
      "Real-time calendar availability engine",
      "Host dashboard for room management",
      "Automated booking confirmations and conflict prevention",
      "Secure user authentication (Better Auth)",
    ],
    challenges: "Handling time-zone discrepancies and ensuring double-bookings were impossible proved difficult. I learned to leverage MongoDB's querying capabilities to block overlapping date ranges efficiently. Building the interactive calendar UI from scratch also sharpened my React state management skills.",
    futureImprovements: [
      "Develop a recurring booking feature for long-term study groups.",
      "Integrate a real-time chat system for seamless communication between space owners and students.",
      "Add a review and rating system for individual study spaces.",
      "Implement a waitlist feature with automated notifications when a booked room is canceled."
    ],
    tech: ["React.js", "Next.js", "Node.js", "Express.js", "MongoDB", "Better Auth"],
    techIcons: [
      { name: "React.js", icon: SiReact, color: "text-[#61DAFB]" },
      { name: "Next.js", icon: SiNextdotjs, color: "text-text-main dark:text-white" },
      { name: "Node.js", icon: SiNodedotjs, color: "text-[#339933]" },
      { name: "Express.js", icon: SiExpress, color: "text-text-main dark:text-white" },
      { name: "MongoDB", icon: SiMongodb, color: "text-[#47A248]" },
    ],
    liveUrl: "https://study-nook-rouge.vercel.app/",
    githubClient: "https://github.com/mehedi-ts/study-nook-client.git",
    githubServer: "https://github.com/mehedi-ts/study-nook-server.git",
    metrics: "Full Stack Application",
    image: "https://i.ibb.co.com/kgg115Ks/studynook.png",
  },
  {
    title: "Book Swap",
    slug: "book-swap",
    category: "Frontend",
    date: "2026-04-05",
    timeline: "3 Weeks",
    shortDesc: "A community-driven book sharing platform for local neighborhoods.",
    description: "Book Swap is a community-driven web platform that allows users to borrow and lend books easily. It promotes a sharing culture, making reading more accessible without the need to purchase every book.",
    overview: "Physical media sharing is returning to popularity, but coordinating swaps is messy. Book Swap is a localized social application designed to map available literature in your neighborhood and facilitate direct peer-to-peer lending without friction.",
    features: [
      "Peer-to-peer inventory browsing",
      "Interactive request and approval pipeline",
      "User reputation and lending history tracking",
      "Responsive, mobile-first book catalog UI",
    ],
    challenges: "Building a complex state pipeline on the frontend to simulate the lending lifecycle (Request -> Approve -> Borrow -> Return) without a robust backend was an interesting exercise in frontend architecture and mock-data management. It taught me how to strictly type and validate states before ever hitting a server.",
    futureImprovements: [
      "Incorporate a map-based UI for discovering nearby available books visually.",
      "Implement a gamified reputation system to reward consistent and reliable lenders.",
      "Add barcode scanning via device camera for quick book inventory uploads.",
      "Integrate push notifications for time-sensitive swap requests and due date reminders."
    ],
    tech: ["Next.js", "React.js", "Tailwind CSS", "Better Auth"],
    techIcons: [
      { name: "Next.js", icon: SiNextdotjs, color: "text-text-main dark:text-white" },
      { name: "React.js", icon: SiReact, color: "text-[#61DAFB]" },
      { name: "Tailwind CSS", icon: SiTailwindcss, color: "text-[#06B6D4]" },
    ],
    liveUrl: "https://book-swap-gilt-tau.vercel.app/",
    githubClient: "https://github.com/mehedi-ts/Book-swap.git",
    metrics: "Book Swap",
    image: "https://i.ibb.co.com/cS05bVBq/Bookswap.png",
  },
  {
    title: "Keen Keeper",
    slug: "keen-keeper",
    category: "Frontend",
    date: "2026-03-20",
    timeline: "5 Weeks",
    shortDesc: "A modern friend management CRM with timeline tracking and data visualizations.",
    description: "Keen Keeper is a modern friend management web application designed to help users maintain meaningful relationships. Users can view friends, explore detailed profiles, and interact through Call, Message, and Video Call features. Each interaction is tracked and stored in a timeline, with a visual statistics dashboard for better insights.",
    overview: "In a world of superficial social media, Keen Keeper focuses on genuine connection. It operates as a personal CRM (Customer Relationship Manager) but built specifically for your friends and family. It helps users remember important details and visually tracks communication frequency to ensure relationships don't fade.",
    features: [
      "Personal relationship dashboard with data visualization",
      "Interaction timeline tracking (Calls, Messages, Meetups)",
      "Detailed, customizable friend profiles",
      "Built entirely with Vite for lightning-fast HMR",
    ],
    challenges: "Integrating Recharts to create meaningful, responsive data visualizations required careful parsing of the timeline data. I had to write custom aggregation utility functions to transform raw interaction logs into chart-ready datasets, which significantly improved my JavaScript data manipulation skills.",
    futureImprovements: [
      "Integrate with Google Calendar and Outlook to automatically sync contact interactions.",
      "Develop AI-powered suggestions for reconnecting with friends based on interaction gaps.",
      "Add a mobile-native version built with React Native for on-the-go logging.",
      "Implement end-to-end encryption for all personal timeline notes and interaction logs."
    ],
    tech: ["React.js", "Tailwind CSS", "Recharts", "Vite"],
    techIcons: [
      { name: "React.js", icon: SiReact, color: "text-[#61DAFB]" },
      { name: "Tailwind CSS", icon: SiTailwindcss, color: "text-[#06B6D4]" },
      { name: "Vite", icon: SiVite, color: "text-[#646CFF]" },
    ],
    liveUrl: "https://keen-keeper-chi-eight.vercel.app/",
    githubClient: "https://github.com/mehedi-ts/Keen-Keeper.git",
    metrics: "Keen Keeper",
    image: "https://i.ibb.co.com/JRcp7QLX/keenkeeper.png",
  },
];
